= Part 1 - The Basics

In this part, you will learn how to set up and configure a simple MVC 1.0 application.

== Objectives

- [ ] Learn how to set up a MVC 1.0 project
- [ ] Understand the difference between vendor specific and standard configuration

== Instructions

=== Setup
Using the tools at hand, create a simple Maven based MVC 1.0 web application with the minimum of configuration.
The project shall display a welcome page and be able to run on both GlassFish 5 and WildFly 11. 
Choose one of the view tecnologies supported by Ozark.

. Set up a Maven Java EE 7 Web project
. Add necessary dependencies for MVC 1.0 API and Ozark
. Configure your application to be able to run both on GlassFish and WildFly using Maven profiles

```
 http://localhost:8080/mvc-hol/app/part-1
 Hello, World!
```

TIP: Ozark is split into separate dependencies for running with Jersey and RESTEasy respectively.

=== Query Parameters
Extend the controller from part 1 to read in a name from a query parameter. 
Use this name to create a personalized greeting, such as 'Hello Duke'.

```
http://localhost:8080/mvc-hol/app/part-1?name=Duke
Hello, Duke!
```

TIP: MVC 1.0 builds on JAX-RS

== Resources

- [ ] Introduction slides
- [ ] JSR 371 Specification Document sections link:https://github.com/mvc-spec/mvc-spec/blob/master/spec/src/main/asciidoc/chapters/controllers.asciidoc[Controllers]
