= Part 1 - The Basics

In this part, you will learn how to set up and configure a simple MVC 1.0 application.

== Objectives

- [ ] Learn how to set up a MVC 1.0 project
- [ ] Understand the difference between vendor specific and standard configuration

== Instructions

=== Setup
Using the tools at hand, create a simple Maven based MVC 1.0 web application with the minimum of configuration.
The project shall display a welcome page and be able to run on both GlassFish 5 and WildFly 11. 
Choose one of the view tecnologies supported by Ozark.

. Set up a Maven Java EE 7 Web project
. Add necessary dependencies for MVC 1.0 API and Ozark
. Configure your application to be able to run both on GlassFish and WildFly using Maven profiles

```
 http://localhost:8080/mvc-hol/app/part-1
 Hello, World!
```

=== Query Parameters
Extend the controller from part 1 to read in a name from a query parameter. 
Use this name to create a personalized greeting, such as 'Hello Duke'.

```
http://localhost:8080/mvc-hol/app/part-1?name=Duke
Hello, Duke!
```

TIP: MVC 1.0 builds on JAX-RS

== Resources

- [ ] Introduction link:MVC1_0-HOL-part1.pdf[slides]
- [ ] link:https://github.com/mvc-spec/mvc-spec/blob/master/spec/src/main/asciidoc/spec.asciidoc[JSR 371 Specification Document]
- [ ] link:https://github.com/ivargrimstad/mvc-hol/tree/start/solution[Empty Project]

TIP: Ozark is split into separate dependencies for running with Jersey and RESTEasy respectively.

``` dependencies
   <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <failOnMissingWebXml>false</failOnMissingWebXml>
        <version.ozark>1.0.0-m03-SNAPSHOT</version.ozark>
    </properties>

  <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>javax</groupId>
                <artifactId>javaee-web-api</artifactId>
                <version>7.0</version>
                <scope>provided</scope>
            </dependency>    
            <dependency>
                <groupId>javax.mvc</groupId>
                <artifactId>javax.mvc-api</artifactId>
                <version>1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.mvc-spec.ozark</groupId>
                <artifactId>ozark-core</artifactId>
                <version>${version.ozark}</version>
            </dependency>  
            <dependency>
                <groupId>org.mvc-spec.ozark</groupId>
                <artifactId>ozark-jersey</artifactId>
                <version>${version.ozark}</version>
            </dependency>  
            <dependency>
                <groupId>org.mvc-spec.ozark</groupId>
                <artifactId>ozark-resteasy</artifactId>
                <version>${version.ozark}</version>
            </dependency>  
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-web-api</artifactId>
            <scope>provided</scope>
        </dependency>
      
        <dependency>
            <groupId>javax.mvc</groupId>
            <artifactId>javax.mvc-api</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.mvc-spec.ozark</groupId>
            <artifactId>ozark-core</artifactId>
        </dependency>  
    </dependencies>
```
``` repository definition
 <repositories>
        <repository>
            <id>sonatype-oss-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

``` profiles for GlassFish and WildFly
  <profiles>
        <profile>
            <id>glassfish</id>
            <activation>
                <activeByDefault>true></activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>org.mvc-spec.ozark</groupId>
                    <artifactId>ozark-jersey</artifactId>
                    <scope>runtime</scope>
                </dependency>
            </dependencies>
        </profile>
        
        <profile>
            <id>wildfly</id>
            <dependencies>
                <dependency>
                    <groupId>org.mvc-spec.ozark</groupId>
                    <artifactId>ozark-resteasy</artifactId>
                    <scope>runtime</scope>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
```