= Part 3 - Useful MVC 1.0 features

== Objectives

- [ ] Learn about scopes
- [ ] Protect your MVC 1.0 application
- [ ] Internationalize your MVC 1.0 application

== Instructions
In this exercise, you will add security to your birthday calculator to protect against Cross-Site Request 
Forgery. You will also address the *double form submission* issue by implementing the POST-Redirect-GET pattern
and internationalize your application. Finally, you will explore the events generated by MVC 1.0 implementation.

```
http://localhost:8080/mvc-hol/app/part-3
Hello, Duke Dukeson from Sweden
Your birthday is in [x] days!
A greeting is registered with id: [UUID]

Happy Birthday!
```

=== Security
Duke don't want anyone to tamper with his birthday greeting. Add protection against Cross-Site Request 
Forgery to your application.

TIP: Check out the `@CsrfValid` annotation provided by MVC 1.0

=== Redirects

Implement the POST-Redirect-GET pattern in your application using the available features of MVC 1.0

TIP: MVC 1.0 defines a custom CDI Scope called `RedirectScoped`

== i18n
Duke wants his computer (browser) settings to tell which country he is from. 
And he wants a greeting message in his local language.

TIP: Check out the `MvcContext`. 

=== Events
Add observers for the default events produces by MVC 1.0 implementations.
todo: move to 2

== Optional

Convert your application (or parts of it) to another view engine supported by Ozark.

== Resources

- [ ] Introduction link:MVC1_0-HOL-part3.pdf[slides]
- [ ] link:https://github.com/mvc-spec/mvc-spec/blob/master/spec/src/main/asciidoc/spec.asciidoc[JSR 371 Specification Document]
