= Part 2 - Core MVC 1.0 Features

In this part you will extend your MVC 1.0 application with more of the supported features of MVC 1.0. 

== Objectives

- [ ] Eplore MVC 1.0
- [ ] Learn about input validation and error handling
- [ ] Integration with CDI

== Instructions

=== Form Parameters
Create a simple form and submit the name to the controller from the form. Use the form parameter to
construct a message to display.

```
http://localhost:8080/mvc-hol/app/part-2/simple
Hello, Duke!
```

TIP: A method may be a controller in MVC 1.0

=== Input Validation
Create a more advanced form with more parameters: First Name, Last Name, Country, Birth Date. Use a form bean to submit the
parameters to the controller. Add Bean validation to your form bean. Handle the validation errors individually for each field in your form in order
to create a better user experience. Calculate the days to next birthday and display this on the greetings page. 
Use a CDI bean to represent the model.

The result after the form submission should be

```
http://localhost:8080/mvc-hol/app/part-2/advanced
Hello, Duke Dukeson from Sweden
Your birthday is in [x] days!
A greeting is registered with id: [UUID]
```

TIP: The default validation error handling in JAX-RS is a one-size-fits-all approach.

``` Sample convenience Class for messages
@Named
@RequestScoped
public class Messages implements Serializable {

    private static final long serialVersionUID = 601263646224546642L;

    private List<ValidationError> errors = new ArrayList<>();

    public void setErrors(List<ValidationError> messages) {
        this.errors = messages;
    }
    
    public List<String> getErrors() {
        return errors.stream()
                .map(ValidationError::getMessage)
                .collect(toList());
    }
    
    public String getMessage(String param) {
        return errors.stream()
                .filter(v -> v.getParamName().equals(param))
                .map(ValidationError::getMessage)
                .findFirst()
                .orElse("");
    }
}
```

``` Sample Service for calculating days to birthday
@RequestScoped
public class BirthDayService {

    public int calculateDaysToBirthday(final String birthDate) {

        final LocalDate now = LocalDate.now();
        final LocalDate bdThisYear = parse(birthDate, DateTimeFormatter.ISO_DATE).withYear(now.getYear());        
        
        if (bdThisYear.isAfter(now)) {
            return (int) now.until(bdThisYear, DAYS);
        } else {
            return (int) now.until(bdThisYear.plusYears(1), DAYS);
        }
    }
}
```

== i18n
Duke wants 

== Resources

- [ ] Introduction slides
- [ ] JSR 371 Specification Document sections
- [ ]

