= Part 2 - Core MVC 1.0 Features

In this part you will extend your MVC 1.0 application with more of the supported features of MVC 1.0. 

== Objectives

- [ ] Eplore MVC 1.0
- [ ] Learn about input validation and error handling
- [ ] Integration with CDI

== Instructions

=== Form Parameters
Create a simple form and submit the name to the controller from the form. Use the form parameter to
construct a message to display.

```
http://localhost:8080/mvc-hol/app/part-2/simple
Hello, Duke!
```

TIP: A method may be a controller in MVC 1.0

=== Input Validation
Create a more advanced form with more parameters: First Name, Last Name, Country, Birth Date. Use a form bean to submit the
parameters to the controller. Add Bean validation to your form bean. Handle the validation errors individually for each field in your form in order
to create a better user experience. Calculate the days to next birthday and display this on the greetings page. 
Use a CDI bean to represent the model.

The result after the form submission should be

```
http://localhost:8080/mvc-hol/app/part-2/advanced
Hello, Duke Dukeson from Sweden
Your birthday is in [x] days!
A greeting is registered with id: [UUID]
```

. Create a form bean class with the attributes in the form
. Add validation to the attributes, such as *not null*, *length*, *pattern* etc.
. Map the validation errors to the attributes in the form e.g. by creating a CDI scoped messages class for this purpose.
. Create a CDI scoped been to send information back to the greetings view.

TIP: The default validation error handling in JAX-RS is a one-size-fits-all approach that can be disabled with the `@ValidateOnExecution(type = NONE)` annotation. 

Due to issues witih Jersey, the annotation-based approach does not work, so validation will have to be disabled globally
by XML configuration. Create a file called `validation.xml` in the `src/main/resources/META-INF` folder.

``` Workaround for GlassFish
<?xml version="1.0" encoding="UTF-8"?>
<validation-config xmlns="http://jboss.org/xml/ns/javax/validation/configuration"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://jboss.org/xml/ns/javax/validation/configuration validation-configuration-1.1.xsd"
                   version="1.1">

  <executable-validation enabled="true">
    <default-validated-executable-types>
      <executable-type>NONE</executable-type>
    </default-validated-executable-types>
  </executable-validation>

</validation-config>
```

Use this provided service implementation to calculate number of days to next birthday (or feel free to implement your own...).

``` Sample Service for calculating days to birthday
@RequestScoped
public class BirthDayService {

    public int calculateDaysToBirthday(final String birthDate) {

        final LocalDate now = LocalDate.now();
        final LocalDate bdThisYear = parse(birthDate, DateTimeFormatter.ISO_DATE).withYear(now.getYear());        
        
        if (bdThisYear.isAfter(now)) {
            return (int) now.until(bdThisYear, DAYS);
        } else {
            return (int) now.until(bdThisYear.plusYears(1), DAYS);
        }
    }
}
```

== Resources

- [ ] Introduction slides
- [ ] JSR 371 Specification Document sections
- [ ]

